const nutritionFacts = [
    {
        id: 1,
      img: "coffee_detail.png",
      mass: "9oz.",
      servingSize: "212.9 g",
      servingPerContainer: "1",
      calories: "6.9",
      caloriesFromFat: "0.0",
      totalFat: "<0.1 g",
      totalFat_daily: "0%",
      saturatedFat: "<0.1 g",
      saturatedFat_daily: "0%",
      transFat: "<0.1 g",
      cholesterol: "<3 mg",
      sodium: "<2 mg",
      sodium_daily: "0%",
      totalCarbohydrates: "0.0 g",
      totalCarbohydrates_daily: "0%",
      dietaryFiber: "<1 g",
      dietaryFiber_daily: "0%",
      totalSugar: "<1.0 g",
      protein: "0.9 g",
      iron_daily: "0%",
      calcium_daily: "4%",
      allergensAr: "الحبوب",
      allergensEn: "GRAIN"
    },
    {
        id: 2,
      img: "coffee_detail.png",
      mass: "9oz.",
      servingSize: "212.9 g",
      servingPerContainer: "1",
      calories: "6.9",
      caloriesFromFat: "0.0",
      totalFat: "<0.1 g",
      totalFat_daily: "0%",
      saturatedFat: "<0.1 g",
      saturatedFat_daily: "0%",
      transFat: "<0.1 g",
      cholesterol: "<3 mg",
      sodium: "<2 mg",
      sodium_daily: "0%",
      totalCarbohydrates: "0.0 g",
      totalCarbohydrates_daily: "0%",
      dietaryFiber: "<1 g",
      dietaryFiber_daily: "0%",
      totalSugar: "<1.0 g",
      protein: "0.9 g",
      iron_daily: "0%",
      calcium_daily: "4%",
      allergensAr: "الحبوب",
      allergensEn: "GRAIN"
    },
  ]